### ISSUE TITLE
Error: unrecognized cop or department Standard/BlockSingleLineBraces under rubocop

### ISSUE THREAD

**Issue by fidalgo** [standardrb/standard#569]
`cat .rubocop.yml `
```
require:
  - standard
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml

Rails:
  Enabled: true
````

`bundle exec rubocop`
```
Error: unrecognized cop or department Standard/BlockSingleLineBraces found in /home/fidalgo/.local/share/rtx/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/standard-custom-1.0.1/config/base.yml
```

```
        Ruby version: 3.2.1
   Current directory: /home/fidalgo/secret/project
     RuboCop version: 1.52.1
    Standard version: 1.30.1
Standard config file: [No file found]

```

I have no issues running with standard, but running under rubocop it errors.

PS: I have several projects that do not use standard 🤦, so I had to configure my editor (nvim with null-ls) to run rubocop instead.

**Comment by searls** [comment]
While this usage is not supported, you probably need to add `standard-custom` and `standard-performance` as those have been spun out of the main gem

**Comment by desheikh** [comment]
@searls I think this is originating from this [commit](https://github.com/standardrb/standard/commit/95eeb20df732705e852d30771b6472a57fdac9ee#diff-b6f99d227d6a4b1b0a3c7a789d6be865ac39fb3847262b5b5d8f68d74a7cd1c1)
which remove the include for `block_single_line_braces`
 
It doesn't look like standard-custom is explicitly [requiring](https://github.com/standardrb/standard-custom/blob/main/lib/standard/custom.rb) the cop.

**Comment by searls** [comment]
Ah, standard-custom does require the cop but it waits until it's loaded as a lint_roller plugin: https://github.com/standardrb/standard-custom/blob/6ca2f3af51cfb709122ca416ac1fc832c7e356bb/lib/standard/custom/plugin.rb#L21

**Comment by desheikh** [comment]
Thanks, for context my team uses standard via rubocop as well so fixing this upstream would be very useful.
I've pushed up a [PR](https://github.com/standardrb/standard-custom/pull/5), if that works.

**Comment by mjgiarlo** [comment]
@searls I was not. That fixes us up. 🍻

**Comment by luizkowalski** [comment]
hey 👋🏻 

I'm also seeing this error. I tried to require the gem on my config but it still doesn't work:


```
# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - standard-custom
  - rubocop-performance
  - rubocop-rails

# Copying Standard Rules
inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml
  standard-rails: config/base.yml
```

I keep getting this: `Error running diagnostics: unrecognized cop or department Standard/BlockSingleLineBraces found in /Users/luiz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/standard-custom-1.0.1/config/base.yml`

**Comment by desheikh** [comment]
@luizkowalski you need to be on standard-custom-1.0.2

**Comment by luizkowalski** [comment]
Weird...I am using 1.0.2 as my lock file shows

```
  standard (1.30.1)
      language_server-protocol (~> 3.17.0.2)
      lint_roller (~> 1.0)
      rubocop (~> 1.52.0)
      standard-custom (~> 1.0.0)
      standard-performance (~> 1.1.0)
    standard-custom (1.0.2)
```

manually uninstalling `standard-custom` with `gem uninstall standard-custom` and selecting v1.0.1 worked
